"""Configurations for dronevis"""
from typing import Dict, Any, Callable, Tuple, List

from dronevis.utils.control_utils import (
    detect_tag,
    activate_gps,
    activate_navdata,
    indoor,
    outdoor,
    nervosity_level,
    max_altitude,
    goto_gps_point,
    flip,
)

SUPPORTED_CONFIG: Dict[str, Callable[[Any], List[Tuple[str, str]]]] = {
    "detect_tag": detect_tag,
    "activate_navdata": activate_navdata,
    "activate_gps": activate_gps,  # Data activation
    "indoor": indoor,
    "outdoor": outdoor,
    "nervosity_level": nervosity_level,
    "max_altitude": max_altitude,  # One-time config
}

AUTONOMOUS_FLIGHT = {"gps": goto_gps_point}
ANIMATIONS = {"flip": flip}
ANIMATIONS_INFOS = {"flip": "(side)"}

MODELS_URLS = {
    "gesture_recognition": [
        "https://drive.google.com/uc?export=download&id=1FTJWeavbHwmu9Vkr_M5k5mV4Lt8sWGFo",
        "gesture_recognition.pth",
    ],
    "dnn_face_detection_caffee": [
        "https://drive.google.com/uc?export=download&id=1xC99ZJFZbjw7jQUtMmLmFtGEOm3eJEBQ",
        "res10_300x300_ssd_iter_140000_fp16.caffemodel",
    ],
    "dnn_face_detection_protof": [
        "https://drive.google.com/uc?export=download&id=1k5Bp7dYL5eKC38mtUb6YFmkX7YFiWaA1",
        "deploy.prototxt",
    ],
    "dnn_face_detection_tf": [
        "https://drive.google.com/uc?export=download&id=1A3tUaJxTA4dkoY7kaky87ITkL3ovh4gy",
        "opencv_face_detector_uint8.pb",
    ],
    "dnn_face_detection_tf_txt": [
        "https://drive.google.com/uc?export=download&id=1sCEe7AujTd0OiJg-3ieNB-GjFQOf4Bz3",
        "opencv_face_detector.pbtxt",
    ],
    "cnn_face_detection": [
        "https://drive.google.com/uc?export=download&id=1ttZzN2x-DzkhuKDxZxEQtp5bu6794dWD",
        "mmod_human_face_detector.dat",
    ],
}

GESTURES_LABELS = {
    "Down": 0,
    "Forward": 1,
    "Left": 2,
    "Right": 3,
    "Stop": 4,
    "Up": 5,
}


COCO_NAMES = [
    "__background__",
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "N/A",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "N/A",
    "backpack",
    "umbrella",
    "N/A",
    "N/A",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "N/A",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "N/A",
    "dining table",
    "N/A",
    "N/A",
    "toilet",
    "N/A",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "N/A",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]
COCO_NAMES_v4 = [
    "person",
    "bicycle",
    "car",
    "motorbike",
    "aeroplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "sofa",
    "pottedplant",
    "bed",
    "diningtable",
    "toilet",
    "tvmonitor",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
]
