"""Configurations for dronevis GUI"""
# colors
MAIN_COLOR = "#161925"
BUTTON_COLOR = "#5C95FF"
LIGHT_MAIN_COLOR = "#04327a"
WHITE_COLOR = "#fff"
LIGHT_GREEN_COLOR = "#55eb75"
GREEN_COLOR = "green"
RED_COLOR = "#FF0000"
FONT_COLOR = "#FAF9F9"

# fonts
MAIN_FONT_FAMILY = "monofur for Powerline"
MAIN_FONT_SIZE = 14
HEADER_FONT_SIZE = 18
MAIN_FONT = (MAIN_FONT_FAMILY, MAIN_FONT_SIZE, "bold")
HEADER_FONT = (MAIN_FONT_FAMILY, HEADER_FONT_SIZE, "bold")

# arrows
VERTICAL_ARROW_SIZE = (28, 30)
HORIZONTAL_ARROW_SIZE = (30, 28)

# X, Y LIMITS
GUI_X_LIMIT = 20
GUI_Y_LIMIT = 50

# Miscellaneous
INDEX_STEP = 0.2
MAX_VELOCITY = 2.0  # m/s
MILLI_TO_METER_FACTOR = 1 / 1000.0
MAX_ANGLE = 360.0
TOGGLE_SIZE = (100, 40)
