Document: dronevis
Title: Debian dronevis Manual
Author: <insert document author here>
Abstract: This manual describes what dronevis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dronevis/dronevis.sgml.gz

Format: postscript
Files: /usr/share/doc/dronevis/dronevis.ps.gz

Format: text
Files: /usr/share/doc/dronevis/dronevis.text.gz

Format: HTML
Index: /usr/share/doc/dronevis/html/index.html
Files: /usr/share/doc/dronevis/html/*.html
