# colors
MAIN_COLOR = "#01112a"
LIGHT_MAIN_COLOR = "#04327a"
WHITE_COLOR = "#fff"
LIGHT_GREEN_COLOR = "#55eb75"
GREEN_COLOR = "green"
RED_COLOR = "#FF0000"

# fonts
MAIN_FONT_FAMILY = "monofur for Powerline"
MAIN_FONT_SIZE = 14
HEADER_FONT_SIZE = 18
MAIN_FONT = (MAIN_FONT_FAMILY, MAIN_FONT_SIZE, "bold")
HEADER_FONT = (MAIN_FONT_FAMILY, HEADER_FONT_SIZE, "bold")

# arrows
VERTICAL_ARROW_SIZE = (28, 30)
HORIZONTAL_ARROW_SIZE = (30, 28)
