name: build

on:
  push:
    branches: ['release']
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
          pip install -e .
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install build dependencies
        run: |
          pip install build twine wheel
      - name: Build distribution
        run: |
          python -m build
      - name: Upload and check
        run: |
          twine check dist/*
          twine upload dist/* --username ${{secrets.PYPI_USERNAME}} --password ${{secrets.PYPI_PASSWORD}}
